# Generated by Django 6.0.2 on 2026-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(),
        ),
    ]
