# Generated by Django 6.0.2 on 2026-02-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date',
            field=models.DateField(default='2024-12-05'),
            preserve_default=False,
        ),
    ]
